[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor -L defmt"


[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Add `defmt`linking options
  "-C", "link-arg=-Tdefmt.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]
target = "riscv32imc-unknown-none-elf"

[env]
DEFMT_LOG = "trace" # <- can change to info, warn, or error

[unstable]
build-std = ["core", "alloc"]
